apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: abn-amro-coding-tech-tls
  namespace: default  
spec:
  secretName: abn-amro-coding-tech-tls  
  issuerRef:
    name: letsencrypt-prod  
    kind: ClusterIssuer
  dnsNames:
  - "abn-amro-coding.tech"  
